"""results/README.md and results/results.json from a run_results() dict.

Table order is fixed and never reordered by outcome:
    (a) CKS contemporaneous replication, per day, 1 s / 10 s / 60 s
    (b) forward predictability, 1 s to 5 min, per day and pooled, with CIs
    (c) fee hurdle: top-decile edge minus cost with CI, per scenario
    (d) cross-venue lead-lag: trades at 100 ms to 5 s, books at >= 1 s
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from . import fees
from .run import (BOOK_LL_DT_S, CKS_AGG_S, FEATURES, FEATURE_LABEL,
                  TRADE_LL_DT_S, jsonable)


def f(x, nd=3, pct=False) -> str:
    try:
        v = float(x)
    except (TypeError, ValueError):
        return "n/a"
    if not np.isfinite(v):
        return "n/a"
    if pct:
        return f"{100 * v:.{nd}f}%"
    return f"{v:.{nd}f}"


def ci(c, nd=3, pct=False) -> str:
    if not c:
        return "n/a"
    lo, hi = c
    if lo is None or hi is None or not (np.isfinite(lo) and np.isfinite(hi)):
        return "n/a"
    return f"[{f(lo, nd, pct)}, {f(hi, nd, pct)}]"


def hrs(seconds) -> str:
    try:
        return f"{float(seconds) / 3600:.2f} h"
    except (TypeError, ValueError):
        return "n/a"


def _forward_table(fwd: dict, horizons: list, with_ci: bool = True) -> list[str]:
    lines = ["| feature | horizon | OOS R^2 (Campbell-Thompson) | 95% block-bootstrap CI | "
             "HAC t (in-sample, bw) | beta (bps per unit) | folds slope>0 | n test |",
             "|---|---|---|---|---|---|---|---|"]
    for name in FEATURES:
        for h_s in horizons:
            rec = fwd.get((name, h_s)) or fwd.get(f"{name}|{h_s}")
            label = FEATURE_LABEL[name]
            if rec is None:
                continue
            if rec.get("insufficient"):
                lines.append(f"| {label} | {h_s} s | insufficient data "
                             f"(n valid = {rec.get('n_valid', 0):,}) | | | | | |")
                continue
            sa = rec.get("sign_agreement") or (0, 0)
            lines.append(
                f"| {label} | {h_s} s | {f(rec['r2_oos'], 4)} | {ci(rec['ci'], 4)} | "
                f"{f(rec['hac_t'], 2)} (bw {rec['hac_bandwidth']}) | "
                f"{f(rec['hac_beta'], 4)} | {sa[0]}/{sa[1]} | {rec['n_test']:,} |")
    return lines


SYNTHETIC_BANNER = (
    "> **SELF-TEST OUTPUT, NOT A MARKET RESULT.** Every day below comes from "
    "the committed synthetic fixture (`tests/fixtures/make_fixture.py`), whose "
    "price path is generated from a planted mechanism. These tables exist so "
    "the pipeline is exercised end to end and CI fails the moment it stops "
    "producing them. They say nothing about Coinbase, Hyperliquid or BTC.")

MIXED_BANNER = (
    "> **WARNING: this run mixes synthetic fixture days with recorded or "
    "downloaded days.** Pooled rows are therefore not a market result. Run "
    "the fixture on its own manifest (`make smoke`) and real days on "
    "`manifest.json` (`make results`).")


def provenance_banner(results: dict) -> str | None:
    """Banner naming what the numbers came from, or None for a real-data run.

    A reader landing on `results/self-test/README.md` must not be able to
    mistake the fixture tables for a measurement; the `source` column alone
    is not enough, so the banner sits above every table.
    """
    days = results.get("days") or []
    sources: set[str] = set()
    for d in days:
        sources.update(d.get("sources") or [])
    if not days or not sources:
        return None
    if sources <= {"synthetic"}:
        return SYNTHETIC_BANNER
    if "synthetic" in sources:
        return MIXED_BANNER
    return None


def build_markdown(results: dict) -> str:
    p = results["params"]
    days = results["days"]
    pooled = results.get("pooled")
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    L = []
    L.append("# Results")
    L.append("")
    cmd = results.get("command") or "make results"
    L.append(f"Generated {now} by `{cmd}` from `{Path(results['manifest']).as_posix()}` "
             f"({results['n_manifest_files']} hashed files). Parameters: "
             f"{p['bar_s']:g} s bars, max gap {p['max_gap_s']:g} s, k = {p['k_levels']} levels, "
             f"{p['n_folds']} purged {'expanding' if p['expanding'] else 'rolling'} folds, "
             f"{p['n_boot']} block-bootstrap draws, seed {p['seed']}, "
             f"signal cut at the top {int(p['decile'] * 100)}% of |prediction| "
             "(ties kept). Every number below is "
             "regenerated by the command; nothing is typed in by hand.")
    L.append("")
    banner = provenance_banner(results)
    if banner:
        L.append(banner)
        L.append("")
    if not days:
        L.append("**No day is analysable yet.** The manifest lists no Coinbase "
                 "product-day with readable files. Pull a Tardis day with "
                 "`make fetch DAY=YYYY-MM-01` or hash recorded files with "
                 "`python tardis_loader.py hash`, then rerun `make results`.")
        if results.get("skipped"):
            L.append("")
            for s in results["skipped"]:
                L.append(f"- skipped {s['key']}: {s['reason']} ({len(s['missing'])} file(s))")
        return "\n".join(L) + "\n"

    # ---- data ---------------------------------------------------------
    L.append("## Data")
    L.append("")
    L.append("| day | source | files | messages | snapshots | disconnects | bars | segments | "
             "book time | span | snapshot checks, no gap (max mismatch) | checks after a gap | crossed |")
    L.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for d in days:
        s = d["stats"]
        clean = (f"{s.get('n_checks_clean', 0)}: "
                 f"{f(s.get('mismatch_rate_clean_max'), 2, True)}"
                 if s.get("n_checks_clean") else "0")
        gapped = s.get("n_checks_gap", s["n_checks"] - s.get("n_checks_clean", 0))
        gap_txt = (f"{gapped}: {f(s.get('mismatch_rate_gap_max'), 2, True)} max"
                   if gapped else "0")
        L.append(f"| {d['key']} | {','.join(d['sources'])} | {len(d['files'])} | "
                 f"{s['n_msgs']:,} | {s['n_snapshots']} | {s['n_disconnects']} | "
                 f"{s['bars']:,} | {s['segments']} | {hrs(s['covered_s'])} | "
                 f"{hrs(s['span_s'])} | {clean} | {gap_txt} | {s['n_crossed']} |")
    L.append("")
    L.append("Snapshot checks compare the diff-rebuilt book with every resent snapshot. "
             "A check with no preceding disconnect is a pure test of the diff replay and "
             "must be 0%; a check straight after a gap measures the gap as much as the "
             "rebuild, so the two are counted separately. `crossed` counts messages "
             "after which bid >= ask.")
    L.append("")

    # ---- (a) ------------------------------------------------------------
    L.append("## (a) CKS contemporaneous replication")
    L.append("")
    L.append("OLS of mid change on best-level OFI summed over the window, within "
             "contiguous segments. Day-wide R^2 uses one slope for the day; the "
             "30-min figure is the mean R^2 over half-hour windows, which is how "
             "Cont, Kukanov and Stoikov (2014) report about 65% at 10 s.")
    L.append("")
    hdr = "| day |" + "".join(f" R^2 {a} s | 30-min mean R^2 {a} s | n {a} s |" for a in CKS_AGG_S)
    L.append(hdr)
    L.append("|---|" + "---|" * (3 * len(CKS_AGG_S)))
    for d in days:
        row = f"| {d['key']} |"
        for a in CKS_AGG_S:
            c = d["cks"].get(a) or d["cks"].get(str(a)) or {}
            row += (f" {f(c.get('r2'), 3, True)} | {f(c.get('r2_window_mean'), 3, True)} "
                    f"({c.get('n_windows', 0)} win) | {c.get('n', 0):,} |")
        L.append(row)
    L.append("")

    # ---- (b) ------------------------------------------------------------
    L.append("## (b) Forward predictability")
    L.append("")
    L.append("Target: log mid return (bps) from bar close t to t+h, only within one "
             "contiguous segment. Purged walk-forward: training ends h bars before the "
             "test chunk. OOS R^2 benchmarks against the training mean. HAC t is the "
             "full-sample Newey-West t-stat of the slope (bandwidth >= h), an "
             "in-sample quantity shown for scale, not as the verdict.")
    L.append("")
    if pooled:
        L.append(f"### Pooled ({pooled['n_days']} day(s), {pooled['bars']:,} bars)")
        L.append("")
        L.extend(_forward_table(pooled["forward"], p["horizons_s"]))
        L.append("")
    for d in days:
        L.append(f"### {d['key']}")
        L.append("")
        L.extend(_forward_table(d["forward"], p["horizons_s"]))
        L.append("")

    # ---- (c) ------------------------------------------------------------
    L.append("## (c) Fee hurdle")
    L.append("")
    L.append("Edge = mean realised mid move (bps, signed by the prediction) over the "
             "pooled out-of-sample bars whose |prediction| clears its "
             f"{100 - int(p['decile'] * 100)}th percentile, with a block-bootstrap CI. "
             "Ties at that percentile are kept rather than broken, so the `share` "
             "column is what was actually traded and can exceed "
             f"{int(p['decile'] * 100)}%: a single-feature OLS gives every bar with a "
             "zero feature the same prediction, and when the cut lands on that plateau "
             "there is no top decile to speak of. Cost = two fees plus the full spread for "
             "taking (mid-to-mid), two maker fees minus the spread for passive quoting "
             "(assumes both fills, no adverse selection: optimistic). "
             f"Fee schedule as of {fees.FEE_SCHEDULE_DATE}: Coinbase Exchange taker "
             f"{fees.COINBASE_EXCHANGE_TIERS[0][1]:g}-{fees.COINBASE_EXCHANGE_TIERS[-1][1]:g} bps, "
             f"Hyperliquid tier-0 taker {fees.HYPERLIQUID_TAKER_BPS:g} bps "
             f"({fees.HYPERLIQUID_TAKER_BPS_LEGACY:g} bps on the older schedule).")
    L.append("")
    if pooled and pooled["hurdle"]:
        spread = pooled["mean_spread_bps"]
        L.append(f"Mean quoted spread over all pooled bars: {f(spread, 2)} bps. "
                 "Each row is charged the mean spread over the bars IT selected "
                 "(the `spread charged` column), not that average, because a "
                 "signal that fires when the book is wide pays the wide spread.")
        L.append("")
        # `\|` because an unescaped pipe inside a cell ENDS the cell: written
        # bare, `mean |pred| (bps)` split this header into 16 cells against
        # the 14 of the separator and the body, and GitHub then dropped the
        # two right-hand scenario names and shifted every heading after the
        # CI. Table (c) is the one the README calls the answer that matters,
        # so it may not be the one that renders wrong.
        L.append("| feature | horizon | n | share of OOS | edge (bps) | 95% CI | "
                 "mean \\|pred\\| (bps) | spread charged (bps) |"
                 + "".join(f" {r['scenario']} |" for r in fees.hurdle_rows(0.0, 0.0)))
        L.append("|---|---|---|---|---|---|---|---|" + "---|" * len(fees.hurdle_rows(0.0, 0.0)))
        for name in FEATURES:
            for h_s in p["horizons_s"]:
                rec = pooled["hurdle"].get((name, h_s)) or pooled["hurdle"].get(f"{name}|{h_s}")
                if rec is None:
                    continue
                share = f(rec.get("frac"), 1, True)
                if rec.get("n_at_threshold", 0) > 1:
                    share += f" ({rec['n_at_threshold']:,} tied)"
                row = (f"| {FEATURE_LABEL[name]} | {h_s} s | {rec['n']:,} | {share} | "
                       f"{f(rec['edge_bps'], 2)} | {ci(rec['ci'], 2)} | "
                       f"{f(rec['pred_bps'], 2)} | {f(rec.get('spread_bps'), 2)} |")
                for r in rec["rows"]:
                    row += f" {f(r['net_bps'], 2)} |"
                L.append(row)
        L.append("")
        L.append("Columns after the CI are edge minus cost under each scenario, in bps; "
                 "a negative number means the signal does not pay for that way of "
                 "trading it at that horizon.")
    else:
        L.append("No pooled out-of-sample predictions are available (insufficient data).")
    L.append("")

    # ---- (d) ------------------------------------------------------------
    L.append("## (d) Cross-venue lead-lag")
    L.append("")
    L.append("corr(Hyperliquid_t, Coinbase_{t+k}): a peak at k > 0 means Hyperliquid "
             "leads Coinbase by k bins. LLR = sum of squared correlations at positive "
             "lags over negative lags (> 1: Hyperliquid leads). Signed trade flow is "
             "compared at 100 ms to 5 s; mid returns from the books only at 1 s and "
             "5 s, because the Hyperliquid l2Book feed is a 20-level snapshot pushed at "
             "most every 0.5 s. Tardis days carry no Hyperliquid data and show n/a.")
    L.append("")
    L.append("| day | series | bin | n bins | peak lag | peak corr | corr at 0 | LLR |")
    L.append("|---|---|---|---|---|---|---|---|")
    for d in days:
        ll = d.get("leadlag")
        if not ll:
            L.append(f"| {d['key']} | (no Hyperliquid data for this day) | | | | | | |")
            continue
        for dt in TRADE_LL_DT_S:
            r = ll["trades"].get(dt) or ll["trades"].get(str(dt))
            if r:
                lag = "n/a" if r["peak_lag"] is None else f"{r['peak_lag']:+d} ({r['peak_lag_s']:+.1f} s)"
                L.append(f"| {d['key']} | trades ({ll['n_hl_trades']:,} HL / {ll['n_cb_trades']:,} CB) | "
                         f"{dt:g} s | {r['n']:,} | {lag} | {f(r['peak_corr'])} | {f(r['corr0'])} | {f(r['llr'], 2)} |")
        for dt in BOOK_LL_DT_S:
            r = ll["book"].get(dt) or ll["book"].get(str(dt))
            if r:
                lag = "n/a" if r["peak_lag"] is None else f"{r['peak_lag']:+d} ({r['peak_lag_s']:+.1f} s)"
                L.append(f"| {d['key']} | book mid returns | {dt:g} s | {r['n']:,} | {lag} | "
                         f"{f(r['peak_corr'])} | {f(r['corr0'])} | {f(r['llr'], 2)} |")
    L.append("")
    L.append("## Reading it")
    L.append("")
    L.append("(a) is the sanity anchor: if the book rebuild and OFI are right, the "
             "contemporaneous R^2 at 10 s should be large. (b) is the question: an OOS "
             "R^2 whose CI excludes zero at a horizon is predictability at that "
             "horizon. (c) is the answer that matters: edge minus cost. (d) is only "
             "measurable on self-recorded days.")
    return "\n".join(L) + "\n"


def write(results: dict, out_dir: Path) -> tuple[Path, Path]:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    md = out_dir / "README.md"
    js = out_dir / "results.json"
    md.write_text(build_markdown(results), encoding="utf-8")
    with open(js, "w", encoding="utf-8") as fh:
        json.dump(jsonable(results), fh, indent=1)
        fh.write("\n")
    return md, js
